### ISSUE TITLE
Readme example gives me following error

### ISSUE THREAD

**Issue by feruzm** [svk31/steemjs-lib#1]
`TypeError: Api.database_api is not a function`

This error comes from following function, any idea how to fix it? I believe Api is not getting initiated properly. Any help to fix this issue is appreciated. thanks

`tr.process_transaction(login, null, true);`

**Comment by svk31** [comment]
Try looking at this set of tests to see how you can initialize the Api and use the library: https://github.com/svk31/steemjs-lib/blob/master/test/chain/TransactionBuilder.js

The basic syntax is like this: 

```
const options = {
    apis: ["database_api", "network_broadcast_api"],
    url: "wss://this.piston.rocks"
};

var {Client} = require('steem-rpc');
var Api = Client.get(options, true);
Api.initPromise.then(function(res) {
    // Api is now ready
});
```

**Comment by feruzm** [comment]
solved, thank you for steemit.chat clarifications. 

Future note: In TransactionBuilder.js, sometimes Client.get(); requires parameters {url:""},true to initiate Api object.
