### ISSUE TITLE
Transactions fail if the websocket server disconnects/changes APIs

### ISSUE THREAD

**Issue by Someguy123** [svk31/steemjs-lib#2]
Most Steem websocket servers disconnect you after 1 or 2 minutes, and this causes SteemJS to break. Most notably the Transaction builder.

Example code (wait 1-2 minutes for the WebSocket to d/c in the network tab of chrome):

```
            # this.props.user is the user object obtained from Login()
            # this.props.account is the raw account object from get_accounts
            var tr = new window.steemJS.TransactionBuilder();
            let new_data = {
                account: this.props.user.name,
                memo_key: this.props.account.memo_key,
                json_metadata: JSON.stringify(original_userjson)
            }
            tr.add_type_operation("account_update", new_data)
            window.pending_tx = tr.process_transaction(this.props.user, null, true)
            pending_tx.then((res) => {
                console.log('successfully sent?');
            }, (err) => {
                console.error('uh oh error: ', err);
            }).catch((e) => {
                console.error('uh oh CATCH error: ', err);
            });
```

Attempting to send an `account_update` request after the server re-connected will get you

```
{"code":1,"message":"10 assert_exception: Assert Exception\n_local_apis.size() > api_id: 
```

Annoyingly, I cannot figure out how to catch this error, which makes this problem even worse. Standard try/catch doesn't work due to the promise, `.then(succ,err)` doesn't seem to work, nor does `.catch(err)`. Attempting to poke at the window.pending_tx shows that the Promise is permanently stuck in "pending", even when it's successful.

Trying to reset the socket, or just close it via `steemJS.steemRPC.Client.close()` for auto reconnect results in "Pausing until websocket connected" errors, even when using the initPromise.

I attempted to update your SteemRPC in package.json to 0.5.3, but ended up getting more fatal errors (on both normal and minified):

```
ApiInstance.js:78 wsRpc open error: TypeError: Cannot read property 'CONNECTING' of undefined(…)
```

**Comment by keverw** [comment]
I'm looking for a good NPM Module to use for posting, this one seems to be one of the better ones out there. Hoping this can be fixed soon.

**Comment by Someguy123** [comment]
For anyone who needs a temporary fix (@keverw), this is what I use for SteemDNS:

```
// Dirty temporary fix for https://github.com/svk31/steemjs-lib/issues/2
// Pulse the websocket every 20 seconds for block number 1, just to make
// sure the websocket doesn't disconnect.
this.nop = () => {
    var Api = window.steemJS.steemRPC.Client.get(options, true);            
    Api.initPromise.then(function(res) {
        Api.database_api().exec("get_block", [1]).then(function(res) {});
    });
}
setInterval(this.nop, 20000);
```

**Comment by svk31** [comment]
```
ApiInstance.js:78 wsRpc open error: TypeError: Cannot read property 'CONNECTING' of undefined(…)
```

That error was due to me not testing `steem-rpc` properly in the browser after adding reconnecting-websocket support for Node.js. It's been fixed in v0.5.4.

In the browser the lib should reconnect however once you've been disconnected, I'll try to have a look at why that's not happening.

**Comment by svk31** [comment]
I've made some more improvements to `steem-rpc`, in my testing it reconnects just fine. Keep in mind that there is an idle threshold parameter that will postpone reconnects if the user is idle. The lib listens to any user events (key press, mouse move, scroll) and reconnects once any of those happens.

If you want to disable this idle threshold, set it to 0 when initialising steem-rpc.

```
var Api = Client.get({idleThreshold: 0}, true);
```

**Comment by svk31** [comment]
I've fixed this in a recent release of steem-rpc, it was due to the apis not being reinitialized after disconnect and reconnect. Should work fine now.
