### ISSUE TITLE
Any way to disable the WS connection closed warnings?

### ISSUE THREAD

**Issue by Someguy123** [svk31/steemjs-lib#4]
Services like steem.ws disconnect you after 60 seconds of inactivity. Rather than handling this nice and quietly, SteemJS screams about it, flooding the console of low-activity scripts (e.g. my pricefeed).

```
WARNING! ws connection wss://node.steem.ws closed
WebSocket: will try to reconnect in 1 sec, attempt #1
connecting to wss://node.steem.ws
```

It would be better if it could inform you only after 2-3 consecutive connection failures, or a simple way to just turn that notice off.

**Comment by svk31** [comment]
I copied your issue to the steem-rpc repo as that's where that code is. I'll wrap the outputs in a debug variable check so you can activate them if needed.
