### ISSUE TITLE
Transactionbuilder failing even in test

### ISSUE THREAD

**Issue by hazinstore** [svk31/steemjs-lib#7]
I thought the problem might be with my code.  But I just ran the test case and tried to transfer 1 SBD from me to ghostwriter, there is something seriously broken here.  This the error log output.

`SteemApi.js:29 SteemApi error: get_required_signatures [{"ref_block_num":0,"ref_block_prefix":0,"expiration":"1970-01-01T00:00:00","operations":[[2,{"from":"williambanks","to":"ghostwriter","amount":"1 sbd sbd","memo":"steembux test"}]],"extensions":[],"signatures":[]},["STM67VpFREmrPSdZs9oePZteUJ5BEUNfmz6CUdkvckrFkaLXkeyEj"]] {"code":1,"message":"4 parse_error_exception: Parse Error\nCouldn't parse int64_t\n    {}\n    th_a  string.cpp:100 to_int64\nrethrow\n    {\"from\":\"1 sbd sbd\"}\n    th_a  asset.cpp:77 from_string","data":{"code":4,"name":"parse_error_exception","message":"Parse Error","stack":[{"context":{"level":"error","file":"string.cpp","line":100,"method":"to_int64","hostname":"","thread_name":"th_a","timestamp":"2016-10-24T11:48:36"},"format":"Couldn't parse int64_t","data":{}},{"context":{"level":"warn","file":"asset.cpp","line":77,"method":"from_string","hostname":"","thread_name":"th_a","timestamp":"2016-10-24T11:48:36"},"format":"rethrow","data":{"from":"1 sbd sbd"}}]}}`

**Comment by hazinstore** [comment]
The error is here...

```
get_required_signatures(available_keys) {

        if (!available_keys.length) { return Promise.resolve([]); }
        var tr_object = ops.signed_transaction.toObject(this);
        // console.log('... tr_object',tr_object)
        //DEBUG console.log('... tr_object',tr_object)
        return Api.database_api().exec( "get_required_signatures", [tr_object, available_keys]).then(function(required_public_keys){
            // DEBUG console.log('... get_required_signatures',required_public_keys)
            return required_public_keys;
        });
    }
```

Is there a valid reason why we are accessing an external server to try and get required signatures instead of just signing with the public keys we're given in the preceding checkkeys function?

```
activeLogin.checkKeys({
                    accountName: passAccount,
                    password: password,
                    auths: {
                        active: account.active.key_auths
                    }}
                );
```

**Comment by svk31** [comment]
Which test is this?

**Comment by hazinstore** [comment]
This one...
https://github.com/svk31/steemjs-lib/blob/master/test/chain/TransactionBuilder.js

```
    it("Add transfer operation", function(done) {
        let tr = new TransactionBuilder();
        tr.add_type_operation("transfer", {
            from: passAccount,
            to: "svk",
            amount: "0.001 SBD",
            memo: new Buffer("Test transfer operation", "utf8")
        });

        tr.process_transaction(activeLogin, null, true).then(res => {
            done();
        })
    });
```

I changed svk to ghostwriter and I used a string "steembux test" as memo and changed the amount to 1.00 and then used my own actual credentials in the config file.

**Comment by svk31** [comment]
I meant which specific test is it that fails, since they all work for me..

Did you try without changing the memo?

**Comment by hazinstore** [comment]
Yes, but when I try to do that I get Buffer is not defined, perhaps because I'm doing it in the browser.  Does memo have to be a buffer for some reason?

**Comment by svk31** [comment]
I believe so, can't really tell you why though I'm afraid.

**Comment by hazinstore** [comment]
Ohh looks like changing the amount to "1.00 SBD" from "1 SBD" got past it, but now I'm getting 

`SteemApi.js:33 SteemApi error: broadcast_transaction_with_callback [null,{"ref_block_num":17644,"ref_block_prefix":3442937367,"expiration":"2016-10-24T12:32:08","operations":[[2,{"from":"williambanks","to":"ghostwriter","amount":"1.00 SBD","memo":""}]],"extensions":[],"signatures":["1f6aff0e852b12e2e34f69c02a179215227240ce2dafb476f7b857b88b7b40d87818217e056031e3f78edf7bdecd74cb1f7658841d3e4dacf4a946934d77d46079"]}] {"code":1,"message":"10 assert_exception: Assert Exception\nfalse: invalid symbol\n    {}\n    th_a  database.cpp:3588 get_balance\n\n    {\"op\":[\"transfer\",{\"from\":\"williambanks\",\"to\":\"ghostwriter\",\"amount\":\"1.00 SBD\",\"memo\":\"\"}]}\n    th_a  database.cpp:3023 _apply_transaction\n\n    {\"trx\":{\"ref_block_num\":17644,\"ref_block_prefix\":3442937367,\"expiration\":\"2016-10-24T12:32:08\",\"operations\":[[\"transfer\",{\"from\":\"williambanks\",\"to\":\"ghostwriter\",\"amount\":\"1.00 SBD\",\"memo\":\"\"}]],\"extensions\":[],\"signatures\":[\"1f6aff0e852b12e2e34f69c02a179215227240ce2dafb476f7b857b88b7b40d87818217e056031e3f78edf7bdecd74cb1f7658841d3e4dacf4a946934d77d46079\"]}}\n    th_a  database.cpp:3027 _apply_transaction\n\n    {\"trx\":{\"ref_block_num\":17644,\"ref_block_prefix\":3442937367,\"expiration\":\"2016-10-24T12:32:08\",\"operations\":[[\"transfer\",{\"from\":\"williambanks\",\"to\":\"ghostwriter\",\"amount\":\"1.00 SBD\",\"memo\":\"\"}]],\"extensions\":[],\"signatures\":[\"1f6aff0e852b12e2e34f69c02a179215227240ce2dafb476f7b857b88b7b40d87818217e056031e3f78edf7bdecd74cb1f7658841d3e4dacf4a946934d77d46079\"]}}\n    th_a  database.cpp:697 push_transaction","data":{"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"database.cpp","line":3588,"method":"get_balance","hostname":"","thread_name":"th_a","timestamp":"2016-10-24T12:31:51"},"format":"false: invalid symbol","data":{}},{"context":{"level":"warn","file":"database.cpp","line":3023,"method":"_apply_transaction","hostname":"","thread_name":"th_a","timestamp":"2016-10-24T12:31:51"},"format":"","data":{"op":["transfer",{"from":"williambanks","to":"ghostwriter","amount":"1.00 SBD","memo":""}]}},{"context":{"level":"warn","file":"database.cpp","line":3027,"method":"_apply_transaction","hostname":"","thread_name":"th_a","timestamp":"2016-10-24T12:31:51"},"format":"","data":{"trx":{"ref_block_num":17644,"ref_block_prefix":3442937367,"expiration":"2016-10-24T12:32:08","operations":[["transfer",{"from":"williambanks","to":"ghostwriter","amount":"1.00 SBD","memo":""}]],"extensions":[],"signatures":["1f6aff0e852b12e2e34f69c02a179215227240ce2dafb476f7b857b88b7b40d87818217e056031e3f78edf7bdecd74cb1f7658841d3e4dacf4a946934d77d46079"]}}},{"context":{"level":"warn","file":"database.cpp","line":697,"method":"push_transaction","hostname":"","thread_name":"th_a","timestamp":"2016-10-24T12:31:51"},"format":"","data":{"trx":{"ref_block_num":17644,"ref_block_prefix":3442937367,"expiration":"2016-10-24T12:32:08","operations":[["transfer",{"from":"williambanks","to":"ghostwriter","amount":"1.00 SBD","memo":""}]],"extensions":[],"signatures":["1f6aff0e852b12e2e34f69c02a179215227240ce2dafb476f7b857b88b7b40d87818217e056031e3f78edf7bdecd74cb1f7658841d3e4dacf4a946934d77d46079"]}}}]}}`

**Comment by hazinstore** [comment]
Have you tested transfers by setting the last flag on transactionbuilder to true?
`tr.process_transaction(activeLogin, null, true)`

**Comment by svk31** [comment]
No you need the symbol, and actually you also need the correct decimal precision; so "1.00 SBD" does not work, but "1.000 SBD" will work.

**Comment by hazinstore** [comment]
Oh crap ok, let me try that then.

**Comment by hazinstore** [comment]
Ok seems to be working now...
https://steemd.com/@ghostwriter

So the problem was precision and symbol.  I'm going to patch my version of this to fix that, maybe split the amount field and add a currency field?

**Comment by svk31** [comment]
You're right actually that it's probably a good idea to rewrite it to handle it in a more logical way in the library even though steemd expects it in this way. I might patch it so you can define amounts using symbol: "SBD", and amount: 1 for example, and the library will then format it properly.

**Comment by hazinstore** [comment]
You want to do that?  I was going to add it to my todo list, but if everything on my todo list needs to be done before I die, then I'm going to need to live forever in order to get it all done. ;)

**Comment by hazinstore** [comment]
Hey I'm not seeing an API call for it, but is there a way to be notified when a new transaction comes through?  Polling in a loop seems horribly inefficient.

**Comment by hazinstore** [comment]
Oh also, memo as a string works perfectly fine here.

**Comment by svk31** [comment]
Good to know about the memo, might just be a leftover from the BTS code that's not needed anymore.

steemd doesn't have any notifications functionality I'm afraid, so no.
