### ISSUE TITLE
Constant disconnecting/signature failures?

### ISSUE THREAD

**Issue by Someguy123** [svk31/steemjs-lib#8]
This seems to be a recurring issue in my Steem Feed script, and I don't understand it.

It can happen once per day, or it can happen once per week, or it can happen every few hours.

One of the messages I get is:

    (node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 164): Error: SteemApi error:get_required_signatures[object Object],STM5QV...{}

Another is:

```
SteemApi error: get_required_signatures [ { ref_block_num: 0,
    ref_block_prefix: 0,
    expiration: '1970-01-01T00:00:00',
    operations: [ [Object] ],
    extensions: [],
    signatures: [] },
  [ 'GLS...' ] ] "connection closed"
```

**Comment by williambanks** [comment]
It doesn't seem to be able to detect when the websocket is disconnected.  That's the root of the problem.  When this happens it should catch it and retry the connection.

**Comment by Someguy123** [comment]
@svk31  ?????

**Comment by Jolly-Pirate** [comment]
Having the same issue. Please fix that.

```
SteemApi error: get_required_signatures [ { ref_block_num: 0,
etc...
```

**Comment by propertunist** [comment]
I'm seeing this now too - the script worked fine for days and then this started about 24 hours ago with no changes having been made at my end to anything.

**Comment by JCBauza** [comment]
I get this error everytime I launch it :(

**Comment by svk31** [comment]
This library was abandoned a long time ago and most likely no longer works due to changes in the STEEM apis. Please use the official js library instead: https://github.com/steemit/steem-js
